SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS household_finance_settings (
    household_id BIGINT UNSIGNED PRIMARY KEY,
    monthly_budget DECIMAL(12,2) NOT NULL DEFAULT 600.00,
    waste_target_percent DECIMAL(5,2) NOT NULL DEFAULT 5.00,
    savings_target_amount DECIMAL(12,2) NOT NULL DEFAULT 100.00,
    price_increase_alert_percent DECIMAL(5,2) NOT NULL DEFAULT 15.00,
    updated_by_member_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_finance_settings_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_finance_settings_member FOREIGN KEY (updated_by_member_id) REFERENCES household_members(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS household_suppliers (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(180) NOT NULL,
    supplier_type ENUM('grocery','farm','warehouse','market','online','restaurant_supply','other') NOT NULL DEFAULT 'grocery',
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    created_by_member_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_household_suppliers_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_household_suppliers_member FOREIGN KEY (created_by_member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    UNIQUE KEY uq_household_supplier_name (household_id, name),
    INDEX idx_household_suppliers_status (household_id, status, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS food_purchase_records (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    inventory_item_id BIGINT UNSIGNED NOT NULL,
    supplier_id BIGINT UNSIGNED NULL,
    purchased_by_member_id BIGINT UNSIGNED NULL,
    action_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    purchased_on DATE NOT NULL,
    quantity DECIMAL(14,4) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    package_quantity DECIMAL(14,4) NULL,
    package_unit VARCHAR(30) NULL,
    total_cost DECIMAL(12,2) NOT NULL,
    unit_cost DECIMAL(14,6) NOT NULL,
    receipt_reference VARCHAR(190) NULL,
    notes TEXT NULL,
    ledger_event_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_purchase_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_purchase_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_supplier FOREIGN KEY (supplier_id) REFERENCES household_suppliers(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_member FOREIGN KEY (purchased_by_member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_ledger FOREIGN KEY (ledger_event_id) REFERENCES food_ledger_events(id) ON DELETE SET NULL,
    UNIQUE KEY uq_purchase_household_action (household_id, action_key),
    INDEX idx_purchase_household_date (household_id, purchased_on, id),
    INDEX idx_purchase_item_date (household_id, inventory_item_id, purchased_on, id),
    INDEX idx_purchase_supplier_item (household_id, supplier_id, inventory_item_id, purchased_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_cost_basis (
    household_id BIGINT UNSIGNED NOT NULL,
    inventory_item_id BIGINT UNSIGNED NOT NULL,
    unit VARCHAR(30) NOT NULL,
    weighted_unit_cost DECIMAL(14,6) NOT NULL,
    quantity_costed DECIMAL(14,4) NOT NULL,
    source_purchase_id BIGINT UNSIGNED NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (household_id, inventory_item_id),
    CONSTRAINT fk_cost_basis_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_cost_basis_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_cost_basis_purchase FOREIGN KEY (source_purchase_id) REFERENCES food_purchase_records(id) ON DELETE SET NULL,
    INDEX idx_cost_basis_updated (household_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS food_waste_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    inventory_item_id BIGINT UNSIGNED NULL,
    prepared_food_batch_id BIGINT UNSIGNED NULL,
    member_id BIGINT UNSIGNED NULL,
    action_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    waste_type ENUM('spoiled','composted','discarded','overproduction','trim_loss','expired','damaged','other') NOT NULL,
    quantity DECIMAL(14,4) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    estimated_value DECIMAL(12,2) NOT NULL DEFAULT 0,
    reason VARCHAR(500) NULL,
    occurred_on DATE NOT NULL,
    ledger_event_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_waste_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_waste_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_waste_prepared FOREIGN KEY (prepared_food_batch_id) REFERENCES prepared_food_batches(id) ON DELETE SET NULL,
    CONSTRAINT fk_waste_member FOREIGN KEY (member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    CONSTRAINT fk_waste_ledger FOREIGN KEY (ledger_event_id) REFERENCES food_ledger_events(id) ON DELETE SET NULL,
    UNIQUE KEY uq_waste_household_action (household_id, action_key),
    INDEX idx_waste_household_date (household_id, occurred_on, id),
    INDEX idx_waste_item_date (household_id, inventory_item_id, occurred_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS recipe_cost_snapshots (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    recipe_id BIGINT UNSIGNED NOT NULL,
    calculation_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    as_of_date DATE NOT NULL,
    servings DECIMAL(8,2) NOT NULL,
    total_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
    cost_per_serving DECIMAL(12,4) NULL,
    priced_ingredient_count INT UNSIGNED NOT NULL DEFAULT 0,
    missing_price_count INT UNSIGNED NOT NULL DEFAULT 0,
    generated_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recipe_cost_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_cost_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_cost_member FOREIGN KEY (generated_by_member_id) REFERENCES household_members(id) ON DELETE RESTRICT,
    UNIQUE KEY uq_recipe_cost_calculation (household_id, calculation_key),
    INDEX idx_recipe_cost_recipe_date (household_id, recipe_id, as_of_date, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS recipe_cost_snapshot_lines (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    recipe_cost_snapshot_id BIGINT UNSIGNED NOT NULL,
    household_id BIGINT UNSIGNED NOT NULL,
    recipe_ingredient_id BIGINT UNSIGNED NOT NULL,
    inventory_item_id BIGINT UNSIGNED NULL,
    ingredient_name_snapshot VARCHAR(180) NOT NULL,
    quantity DECIMAL(14,4) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    unit_cost DECIMAL(14,6) NULL,
    extended_cost DECIMAL(12,4) NULL,
    pricing_status ENUM('priced','missing','unit_mismatch') NOT NULL,
    source_purchase_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recipe_cost_line_snapshot FOREIGN KEY (recipe_cost_snapshot_id) REFERENCES recipe_cost_snapshots(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_cost_line_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_cost_line_ingredient FOREIGN KEY (recipe_ingredient_id) REFERENCES recipe_ingredients(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_cost_line_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_recipe_cost_line_purchase FOREIGN KEY (source_purchase_id) REFERENCES food_purchase_records(id) ON DELETE SET NULL,
    UNIQUE KEY uq_recipe_cost_line_ingredient (recipe_cost_snapshot_id, recipe_ingredient_id),
    INDEX idx_recipe_cost_line_item (household_id, inventory_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS household_finance_snapshots (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    month_start DATE NOT NULL,
    month_end DATE NOT NULL,
    run_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_watermark CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    model_version VARCHAR(40) NOT NULL DEFAULT 'deterministic-v1',
    status ENUM('running','completed','failed') NOT NULL DEFAULT 'running',
    budget_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    purchase_spend DECIMAL(12,2) NOT NULL DEFAULT 0,
    waste_value DECIMAL(12,2) NOT NULL DEFAULT 0,
    household_production_value DECIMAL(12,2) NOT NULL DEFAULT 0,
    preservation_value DECIMAL(12,2) NOT NULL DEFAULT 0,
    estimated_savings DECIMAL(12,2) NOT NULL DEFAULT 0,
    budget_variance DECIMAL(12,2) NOT NULL DEFAULT 0,
    waste_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
    savings_rate_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
    purchase_count INT UNSIGNED NOT NULL DEFAULT 0,
    waste_event_count INT UNSIGNED NOT NULL DEFAULT 0,
    recommendation_count INT UNSIGNED NOT NULL DEFAULT 0,
    generated_by_member_id BIGINT UNSIGNED NOT NULL,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME NULL,
    CONSTRAINT fk_finance_snapshot_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_finance_snapshot_member FOREIGN KEY (generated_by_member_id) REFERENCES household_members(id) ON DELETE RESTRICT,
    UNIQUE KEY uq_finance_snapshot_run (household_id, run_key),
    INDEX idx_finance_snapshot_month (household_id, month_start, status),
    INDEX idx_finance_snapshot_status (household_id, status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_recommendations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    snapshot_id BIGINT UNSIGNED NOT NULL,
    inventory_item_id BIGINT UNSIGNED NULL,
    recommendation_type ENUM('budget_alert','price_increase','compare_supplier','use_first','reduce_waste','bulk_buy','review_data') NOT NULL,
    generation_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(180) NOT NULL,
    rationale TEXT NOT NULL,
    recommended_action TEXT NOT NULL,
    estimated_impact DECIMAL(12,2) NULL,
    priority ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
    due_on DATE NULL,
    status ENUM('pending','accepted','dismissed','completed') NOT NULL DEFAULT 'pending',
    related_task_id BIGINT UNSIGNED NULL,
    acted_by_member_id BIGINT UNSIGNED NULL,
    acted_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_finance_recommendation_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_finance_recommendation_snapshot FOREIGN KEY (snapshot_id) REFERENCES household_finance_snapshots(id) ON DELETE CASCADE,
    CONSTRAINT fk_finance_recommendation_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_finance_recommendation_task FOREIGN KEY (related_task_id) REFERENCES household_tasks(id) ON DELETE SET NULL,
    CONSTRAINT fk_finance_recommendation_actor FOREIGN KEY (acted_by_member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    UNIQUE KEY uq_finance_recommendation_generation (household_id, generation_key),
    INDEX idx_finance_recommendation_status (household_id, status, priority, due_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_lifecycle_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    snapshot_id BIGINT UNSIGNED NULL,
    purchase_id BIGINT UNSIGNED NULL,
    waste_event_id BIGINT UNSIGNED NULL,
    recommendation_id BIGINT UNSIGNED NULL,
    member_id BIGINT UNSIGNED NULL,
    event_type VARCHAR(60) NOT NULL,
    from_status VARCHAR(30) NULL,
    to_status VARCHAR(30) NULL,
    notes TEXT NULL,
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_finance_event_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_finance_event_snapshot FOREIGN KEY (snapshot_id) REFERENCES household_finance_snapshots(id) ON DELETE SET NULL,
    CONSTRAINT fk_finance_event_purchase FOREIGN KEY (purchase_id) REFERENCES food_purchase_records(id) ON DELETE SET NULL,
    CONSTRAINT fk_finance_event_waste FOREIGN KEY (waste_event_id) REFERENCES food_waste_events(id) ON DELETE SET NULL,
    CONSTRAINT fk_finance_event_recommendation FOREIGN KEY (recommendation_id) REFERENCES finance_recommendations(id) ON DELETE SET NULL,
    CONSTRAINT fk_finance_event_member FOREIGN KEY (member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    INDEX idx_finance_events_household_time (household_id, occurred_at, id),
    INDEX idx_finance_events_recommendation (recommendation_id, occurred_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
