SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS household_forecast_settings (
    household_id BIGINT UNSIGNED PRIMARY KEY,
    horizon_days SMALLINT UNSIGNED NOT NULL DEFAULT 90,
    history_days SMALLINT UNSIGNED NOT NULL DEFAULT 90,
    target_self_sufficiency_percent DECIMAL(5,2) NOT NULL DEFAULT 25.00,
    target_buffer_days SMALLINT UNSIGNED NOT NULL DEFAULT 21,
    updated_by_member_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_forecast_settings_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_forecast_settings_member FOREIGN KEY (updated_by_member_id) REFERENCES household_members(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS forecast_snapshots (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    as_of_date DATE NOT NULL,
    horizon_days SMALLINT UNSIGNED NOT NULL,
    history_days SMALLINT UNSIGNED NOT NULL,
    run_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_watermark CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    model_version VARCHAR(40) NOT NULL DEFAULT 'deterministic-v1',
    status ENUM('running','completed','failed') NOT NULL DEFAULT 'running',
    inventory_coverage_score DECIMAL(5,2) NULL,
    self_sufficiency_score DECIMAL(5,2) NULL,
    seasonal_readiness_score DECIMAL(5,2) NULL,
    resilience_score DECIMAL(5,2) NULL,
    projected_shortage_count INT UNSIGNED NOT NULL DEFAULT 0,
    projected_harvest_count INT UNSIGNED NOT NULL DEFAULT 0,
    recommendation_count INT UNSIGNED NOT NULL DEFAULT 0,
    generated_by_member_id BIGINT UNSIGNED NOT NULL,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME NULL,
    CONSTRAINT fk_forecast_snapshots_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_forecast_snapshots_member FOREIGN KEY (generated_by_member_id) REFERENCES household_members(id) ON DELETE RESTRICT,
    UNIQUE KEY uq_forecast_snapshots_run (household_id, run_key),
    INDEX idx_forecast_snapshots_household_date (household_id, as_of_date, status),
    INDEX idx_forecast_snapshots_status (household_id, status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS forecast_item_projections (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    snapshot_id BIGINT UNSIGNED NOT NULL,
    household_id BIGINT UNSIGNED NOT NULL,
    inventory_item_id BIGINT UNSIGNED NOT NULL,
    item_name_snapshot VARCHAR(180) NOT NULL,
    category_name_snapshot VARCHAR(120) NULL,
    unit VARCHAR(30) NOT NULL,
    current_quantity DECIMAL(14,4) NOT NULL DEFAULT 0,
    daily_depletion_rate DECIMAL(14,6) NOT NULL DEFAULT 0,
    planned_demand_quantity DECIMAL(14,4) NOT NULL DEFAULT 0,
    projected_consumption_quantity DECIMAL(14,4) NOT NULL DEFAULT 0,
    projected_harvest_quantity DECIMAL(14,4) NOT NULL DEFAULT 0,
    projected_preservation_quantity DECIMAL(14,4) NOT NULL DEFAULT 0,
    projected_ending_quantity DECIMAL(14,4) NOT NULL DEFAULT 0,
    days_on_hand DECIMAL(10,2) NULL,
    shortage_date DATE NULL,
    production_ratio_percent DECIMAL(5,2) NULL,
    source_event_count INT UNSIGNED NOT NULL DEFAULT 0,
    confidence ENUM('low','medium','high') NOT NULL DEFAULT 'low',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_forecast_projection_snapshot FOREIGN KEY (snapshot_id) REFERENCES forecast_snapshots(id) ON DELETE CASCADE,
    CONSTRAINT fk_forecast_projection_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_forecast_projection_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
    UNIQUE KEY uq_forecast_projection_item (snapshot_id, inventory_item_id),
    INDEX idx_forecast_projection_risk (household_id, shortage_date, days_on_hand)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS self_sufficiency_metrics (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    snapshot_id BIGINT UNSIGNED NOT NULL,
    household_id BIGINT UNSIGNED NOT NULL,
    metric_key VARCHAR(60) NOT NULL,
    numerator DECIMAL(18,4) NULL,
    denominator DECIMAL(18,4) NULL,
    score_percent DECIMAL(5,2) NOT NULL,
    explanation VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_self_metric_snapshot FOREIGN KEY (snapshot_id) REFERENCES forecast_snapshots(id) ON DELETE CASCADE,
    CONSTRAINT fk_self_metric_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    UNIQUE KEY uq_self_metric_key (snapshot_id, metric_key),
    INDEX idx_self_metric_household (household_id, metric_key, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS forecast_recommendations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    snapshot_id BIGINT UNSIGNED NOT NULL,
    projection_id BIGINT UNSIGNED NULL,
    recommendation_type ENUM('restock','plant','preserve','rotate','use_first','increase_buffer','review_data') NOT NULL,
    generation_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(180) NOT NULL,
    rationale TEXT NOT NULL,
    recommended_action TEXT NOT NULL,
    recommended_quantity DECIMAL(14,4) NULL,
    unit VARCHAR(30) NULL,
    priority ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
    due_on DATE NULL,
    status ENUM('pending','accepted','dismissed','completed') NOT NULL DEFAULT 'pending',
    related_task_id BIGINT UNSIGNED NULL,
    acted_by_member_id BIGINT UNSIGNED NULL,
    acted_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_forecast_recommendation_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_forecast_recommendation_snapshot FOREIGN KEY (snapshot_id) REFERENCES forecast_snapshots(id) ON DELETE CASCADE,
    CONSTRAINT fk_forecast_recommendation_projection FOREIGN KEY (projection_id) REFERENCES forecast_item_projections(id) ON DELETE SET NULL,
    CONSTRAINT fk_forecast_recommendation_task FOREIGN KEY (related_task_id) REFERENCES household_tasks(id) ON DELETE SET NULL,
    CONSTRAINT fk_forecast_recommendation_actor FOREIGN KEY (acted_by_member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    UNIQUE KEY uq_forecast_recommendation_generation (household_id, generation_key),
    INDEX idx_forecast_recommendation_status (household_id, status, priority, due_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS seasonal_plan_entries (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    snapshot_id BIGINT UNSIGNED NULL,
    entry_type ENUM('plant','harvest','preserve','purchase','rotate','prepare') NOT NULL,
    generation_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(180) NOT NULL,
    crop_or_item VARCHAR(180) NULL,
    starts_on DATE NOT NULL,
    ends_on DATE NULL,
    expected_quantity DECIMAL(14,4) NULL,
    unit VARCHAR(30) NULL,
    source_type VARCHAR(80) NULL,
    source_id BIGINT UNSIGNED NULL,
    assigned_member_id BIGINT UNSIGNED NULL,
    status ENUM('planned','accepted','completed','dismissed') NOT NULL DEFAULT 'planned',
    notes TEXT NULL,
    acted_by_member_id BIGINT UNSIGNED NULL,
    acted_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_seasonal_entry_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_seasonal_entry_snapshot FOREIGN KEY (snapshot_id) REFERENCES forecast_snapshots(id) ON DELETE SET NULL,
    CONSTRAINT fk_seasonal_entry_assignee FOREIGN KEY (assigned_member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    CONSTRAINT fk_seasonal_entry_actor FOREIGN KEY (acted_by_member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    UNIQUE KEY uq_seasonal_entry_generation (household_id, generation_key),
    INDEX idx_seasonal_entry_window (household_id, starts_on, status),
    INDEX idx_seasonal_entry_source (household_id, source_type, source_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS forecast_lifecycle_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    snapshot_id BIGINT UNSIGNED NULL,
    recommendation_id BIGINT UNSIGNED NULL,
    seasonal_entry_id BIGINT UNSIGNED NULL,
    member_id BIGINT UNSIGNED NULL,
    event_type VARCHAR(50) NOT NULL,
    from_status VARCHAR(30) NULL,
    to_status VARCHAR(30) NULL,
    notes TEXT NULL,
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_forecast_event_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_forecast_event_snapshot FOREIGN KEY (snapshot_id) REFERENCES forecast_snapshots(id) ON DELETE SET NULL,
    CONSTRAINT fk_forecast_event_recommendation FOREIGN KEY (recommendation_id) REFERENCES forecast_recommendations(id) ON DELETE SET NULL,
    CONSTRAINT fk_forecast_event_seasonal FOREIGN KEY (seasonal_entry_id) REFERENCES seasonal_plan_entries(id) ON DELETE SET NULL,
    CONSTRAINT fk_forecast_event_member FOREIGN KEY (member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    INDEX idx_forecast_events_household_time (household_id, occurred_at, id),
    INDEX idx_forecast_events_recommendation (recommendation_id, occurred_at, id),
    INDEX idx_forecast_events_seasonal (seasonal_entry_id, occurred_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
