SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS household_nutrition_settings (
    household_id BIGINT UNSIGNED PRIMARY KEY,
    assessment_window_days SMALLINT UNSIGNED NOT NULL DEFAULT 7,
    minimum_recipe_variety SMALLINT UNSIGNED NOT NULL DEFAULT 5,
    minimum_data_completeness_percent DECIMAL(5,2) NOT NULL DEFAULT 80.00,
    show_optional_targets TINYINT(1) NOT NULL DEFAULT 1,
    updated_by_member_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_nutrition_settings_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_nutrition_settings_member FOREIGN KEY (updated_by_member_id) REFERENCES household_members(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_nutrition_profiles (
    household_id BIGINT UNSIGNED NOT NULL,
    household_member_id BIGINT UNSIGNED NOT NULL,
    dietary_pattern VARCHAR(120) NULL,
    calorie_target DECIMAL(10,2) NULL,
    protein_target_g DECIMAL(10,2) NULL,
    fiber_target_g DECIMAL(10,2) NULL,
    sodium_limit_mg DECIMAL(12,2) NULL,
    added_sugar_limit_g DECIMAL(10,2) NULL,
    target_notes TEXT NULL,
    updated_by_member_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (household_id, household_member_id),
    CONSTRAINT fk_member_nutrition_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_member_nutrition_member FOREIGN KEY (household_member_id) REFERENCES household_members(id) ON DELETE CASCADE,
    CONSTRAINT fk_member_nutrition_actor FOREIGN KEY (updated_by_member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    INDEX idx_member_nutrition_updated (household_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_allergen_rules (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    household_member_id BIGINT UNSIGNED NOT NULL,
    allergen_key VARCHAR(80) NOT NULL,
    severity ENUM('preference','intolerance','allergy') NOT NULL DEFAULT 'preference',
    notes VARCHAR(500) NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    updated_by_member_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_member_allergen_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_member_allergen_member FOREIGN KEY (household_member_id) REFERENCES household_members(id) ON DELETE CASCADE,
    CONSTRAINT fk_member_allergen_actor FOREIGN KEY (updated_by_member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    UNIQUE KEY uq_member_allergen_rule (household_id, household_member_id, allergen_key),
    INDEX idx_member_allergen_active (household_id, household_member_id, active, severity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_nutrition_profiles (
    household_id BIGINT UNSIGNED NOT NULL,
    inventory_item_id BIGINT UNSIGNED NOT NULL,
    basis_quantity DECIMAL(14,4) NOT NULL DEFAULT 1.0000,
    basis_unit VARCHAR(30) NOT NULL,
    calories DECIMAL(12,4) NULL,
    protein_g DECIMAL(12,4) NULL,
    carbohydrate_g DECIMAL(12,4) NULL,
    fat_g DECIMAL(12,4) NULL,
    fiber_g DECIMAL(12,4) NULL,
    total_sugar_g DECIMAL(12,4) NULL,
    added_sugar_g DECIMAL(12,4) NULL,
    sodium_mg DECIMAL(14,4) NULL,
    source_label VARCHAR(190) NULL,
    confidence ENUM('estimated','label','verified') NOT NULL DEFAULT 'estimated',
    updated_by_member_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (household_id, inventory_item_id),
    CONSTRAINT fk_inventory_nutrition_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_nutrition_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_nutrition_actor FOREIGN KEY (updated_by_member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    INDEX idx_inventory_nutrition_updated (household_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_allergen_tags (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    inventory_item_id BIGINT UNSIGNED NOT NULL,
    allergen_key VARCHAR(80) NOT NULL,
    presence ENUM('contains','may_contain','shared_facility') NOT NULL DEFAULT 'contains',
    source_label VARCHAR(190) NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    updated_by_member_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_allergen_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_allergen_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_allergen_actor FOREIGN KEY (updated_by_member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    UNIQUE KEY uq_inventory_allergen_tag (household_id, inventory_item_id, allergen_key),
    INDEX idx_inventory_allergen_active (household_id, allergen_key, active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS recipe_nutrition_snapshots (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    recipe_id BIGINT UNSIGNED NOT NULL,
    calculation_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    as_of_date DATE NOT NULL,
    servings DECIMAL(8,2) NOT NULL,
    total_calories DECIMAL(14,4) NOT NULL DEFAULT 0,
    total_protein_g DECIMAL(14,4) NOT NULL DEFAULT 0,
    total_carbohydrate_g DECIMAL(14,4) NOT NULL DEFAULT 0,
    total_fat_g DECIMAL(14,4) NOT NULL DEFAULT 0,
    total_fiber_g DECIMAL(14,4) NOT NULL DEFAULT 0,
    total_sugar_g DECIMAL(14,4) NOT NULL DEFAULT 0,
    total_added_sugar_g DECIMAL(14,4) NOT NULL DEFAULT 0,
    total_sodium_mg DECIMAL(16,4) NOT NULL DEFAULT 0,
    calories_per_serving DECIMAL(12,4) NULL,
    protein_per_serving_g DECIMAL(12,4) NULL,
    fiber_per_serving_g DECIMAL(12,4) NULL,
    sodium_per_serving_mg DECIMAL(14,4) NULL,
    priced_ingredient_count INT UNSIGNED NOT NULL DEFAULT 0,
    missing_profile_count INT UNSIGNED NOT NULL DEFAULT 0,
    unit_mismatch_count INT UNSIGNED NOT NULL DEFAULT 0,
    allergen_keys JSON NULL,
    generated_by_member_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recipe_nutrition_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_nutrition_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_nutrition_member FOREIGN KEY (generated_by_member_id) REFERENCES household_members(id) ON DELETE RESTRICT,
    UNIQUE KEY uq_recipe_nutrition_calculation (household_id, calculation_key),
    INDEX idx_recipe_nutrition_recipe_date (household_id, recipe_id, as_of_date, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS recipe_nutrition_snapshot_lines (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    recipe_nutrition_snapshot_id BIGINT UNSIGNED NOT NULL,
    household_id BIGINT UNSIGNED NOT NULL,
    recipe_ingredient_id BIGINT UNSIGNED NOT NULL,
    inventory_item_id BIGINT UNSIGNED NULL,
    ingredient_name_snapshot VARCHAR(180) NOT NULL,
    quantity DECIMAL(14,4) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    calculation_status ENUM('calculated','missing_profile','unit_mismatch') NOT NULL,
    calories DECIMAL(12,4) NULL,
    protein_g DECIMAL(12,4) NULL,
    fiber_g DECIMAL(12,4) NULL,
    sodium_mg DECIMAL(14,4) NULL,
    allergen_keys JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recipe_nutrition_line_snapshot FOREIGN KEY (recipe_nutrition_snapshot_id) REFERENCES recipe_nutrition_snapshots(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_nutrition_line_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_nutrition_line_ingredient FOREIGN KEY (recipe_ingredient_id) REFERENCES recipe_ingredients(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_nutrition_line_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE SET NULL,
    UNIQUE KEY uq_recipe_nutrition_line (recipe_nutrition_snapshot_id, recipe_ingredient_id),
    INDEX idx_recipe_nutrition_line_item (household_id, inventory_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meal_nutrition_assessments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    meal_plan_id BIGINT UNSIGNED NOT NULL,
    run_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_watermark CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    model_version VARCHAR(40) NOT NULL DEFAULT 'deterministic-v1',
    status ENUM('running','completed','failed') NOT NULL DEFAULT 'running',
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    member_count INT UNSIGNED NOT NULL DEFAULT 0,
    planned_meal_count INT UNSIGNED NOT NULL DEFAULT 0,
    assessed_meal_count INT UNSIGNED NOT NULL DEFAULT 0,
    missing_recipe_profile_count INT UNSIGNED NOT NULL DEFAULT 0,
    allergen_conflict_count INT UNSIGNED NOT NULL DEFAULT 0,
    recommendation_count INT UNSIGNED NOT NULL DEFAULT 0,
    household_balance_score DECIMAL(5,2) NOT NULL DEFAULT 0,
    data_completeness_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
    generated_by_member_id BIGINT UNSIGNED NOT NULL,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME NULL,
    CONSTRAINT fk_meal_nutrition_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_meal_nutrition_plan FOREIGN KEY (meal_plan_id) REFERENCES meal_plans(id) ON DELETE CASCADE,
    CONSTRAINT fk_meal_nutrition_member FOREIGN KEY (generated_by_member_id) REFERENCES household_members(id) ON DELETE RESTRICT,
    UNIQUE KEY uq_meal_nutrition_run (household_id, run_key),
    INDEX idx_meal_nutrition_plan (household_id, meal_plan_id, status, completed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_nutrition_assessment_lines (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    meal_nutrition_assessment_id BIGINT UNSIGNED NOT NULL,
    household_id BIGINT UNSIGNED NOT NULL,
    household_member_id BIGINT UNSIGNED NOT NULL,
    planned_meal_count INT UNSIGNED NOT NULL DEFAULT 0,
    assessed_meal_count INT UNSIGNED NOT NULL DEFAULT 0,
    distinct_recipe_count INT UNSIGNED NOT NULL DEFAULT 0,
    total_calories DECIMAL(14,4) NOT NULL DEFAULT 0,
    total_protein_g DECIMAL(14,4) NOT NULL DEFAULT 0,
    total_fiber_g DECIMAL(14,4) NOT NULL DEFAULT 0,
    total_sodium_mg DECIMAL(16,4) NOT NULL DEFAULT 0,
    total_added_sugar_g DECIMAL(14,4) NOT NULL DEFAULT 0,
    calorie_target_coverage_percent DECIMAL(7,2) NULL,
    protein_target_coverage_percent DECIMAL(7,2) NULL,
    fiber_target_coverage_percent DECIMAL(7,2) NULL,
    sodium_limit_usage_percent DECIMAL(7,2) NULL,
    allergen_conflict_count INT UNSIGNED NOT NULL DEFAULT 0,
    missing_profile_count INT UNSIGNED NOT NULL DEFAULT 0,
    balance_score DECIMAL(5,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_member_assessment_snapshot FOREIGN KEY (meal_nutrition_assessment_id) REFERENCES meal_nutrition_assessments(id) ON DELETE CASCADE,
    CONSTRAINT fk_member_assessment_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_member_assessment_member FOREIGN KEY (household_member_id) REFERENCES household_members(id) ON DELETE CASCADE,
    UNIQUE KEY uq_member_assessment_line (meal_nutrition_assessment_id, household_member_id),
    INDEX idx_member_assessment_member (household_id, household_member_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nutrition_recommendations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    assessment_id BIGINT UNSIGNED NOT NULL,
    household_member_id BIGINT UNSIGNED NULL,
    recipe_id BIGINT UNSIGNED NULL,
    meal_plan_item_id BIGINT UNSIGNED NULL,
    recommendation_type ENUM('allergen_conflict','protein_gap','fiber_gap','sodium_review','added_sugar_review','variety','data_quality','portion_balance') NOT NULL,
    generation_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(180) NOT NULL,
    rationale TEXT NOT NULL,
    recommended_action TEXT NOT NULL,
    priority ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
    due_on DATE NULL,
    status ENUM('pending','accepted','dismissed','completed') NOT NULL DEFAULT 'pending',
    related_task_id BIGINT UNSIGNED NULL,
    acted_by_member_id BIGINT UNSIGNED NULL,
    acted_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_nutrition_recommendation_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_nutrition_recommendation_assessment FOREIGN KEY (assessment_id) REFERENCES meal_nutrition_assessments(id) ON DELETE CASCADE,
    CONSTRAINT fk_nutrition_recommendation_member FOREIGN KEY (household_member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    CONSTRAINT fk_nutrition_recommendation_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE SET NULL,
    CONSTRAINT fk_nutrition_recommendation_meal FOREIGN KEY (meal_plan_item_id) REFERENCES meal_plan_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_nutrition_recommendation_task FOREIGN KEY (related_task_id) REFERENCES household_tasks(id) ON DELETE SET NULL,
    CONSTRAINT fk_nutrition_recommendation_actor FOREIGN KEY (acted_by_member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    UNIQUE KEY uq_nutrition_recommendation_generation (household_id, generation_key),
    INDEX idx_nutrition_recommendation_status (household_id, status, priority, due_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nutrition_lifecycle_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    household_id BIGINT UNSIGNED NOT NULL,
    assessment_id BIGINT UNSIGNED NULL,
    recipe_nutrition_snapshot_id BIGINT UNSIGNED NULL,
    recommendation_id BIGINT UNSIGNED NULL,
    member_id BIGINT UNSIGNED NULL,
    event_type VARCHAR(60) NOT NULL,
    from_status VARCHAR(30) NULL,
    to_status VARCHAR(30) NULL,
    notes TEXT NULL,
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_nutrition_event_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE CASCADE,
    CONSTRAINT fk_nutrition_event_assessment FOREIGN KEY (assessment_id) REFERENCES meal_nutrition_assessments(id) ON DELETE SET NULL,
    CONSTRAINT fk_nutrition_event_recipe_snapshot FOREIGN KEY (recipe_nutrition_snapshot_id) REFERENCES recipe_nutrition_snapshots(id) ON DELETE SET NULL,
    CONSTRAINT fk_nutrition_event_recommendation FOREIGN KEY (recommendation_id) REFERENCES nutrition_recommendations(id) ON DELETE SET NULL,
    CONSTRAINT fk_nutrition_event_member FOREIGN KEY (member_id) REFERENCES household_members(id) ON DELETE SET NULL,
    INDEX idx_nutrition_events_household_time (household_id, occurred_at, id),
    INDEX idx_nutrition_events_recommendation (recommendation_id, occurred_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;